apiVersion: automation.cloudbees.io/v1alpha1
kind: workflow
name: Evidence gathering example

on:
  push:
    branches:
      - '**'

env:
  EVIDENCE_FILE: evidence_${{ run_id }}.html

jobs:
  build:
    steps:
      - name: Checkout workflow repo code
        uses: cloudbees-io/checkout@v1
      - name: Git global credentials
        uses: cloudbees-io/configure-git-global-credentials@v1
      - name: Clone evidence repo
        uses: docker://alpine/git:latest
        run: |
          git clone https://github.com/gmaxey/evidence.git
      - name: Save evidence file
        uses: docker://bash
        run: |
          cd evidence
          echo << EOF > $EVIDENCE_FILE
          run_id  ${{ cloudbees.run_id }}
          job.id  ${{ job.id }}
          step.internal.id  ${{ step.internal.id }}
          cloudbees.api.url  ${{ cloudbees.api.url }}
          EOF
      - name: Push evidence to workflow repo
        uses: docker://alpine/git:latest
        shell: sh
        run: |
          cd evidence
          git add $EVIDENCE_FILE
          git config --global user.email "gregorymaxey@yahoo.com"
          git config --global user.name "Greg Maxey"
          git commit . -m "Evidence from ${{ run_id }}"
          git remote remove origin
          git remote add origin https://${{ secrets.GITHUB_TOKEN}}@github.com/gmaxey/evidence
          git push --set-upstream origin main
